# Generated by Django 5.2.10 on 2026-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='ticker',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
